name: Publish articles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "GitHub Actions is working!"
